name: Update Space Shooter Game

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 1 * * *'  # Daily at midnight 1 UTC

permissions:
  contents: write

jobs:
  update-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: czl9707/gh-space-shooter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: 'game.gif'
          strategy: 'random'
